name: "Bug Report"
description: Create a new ticket for a bug.
labels: [
  "Bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a detailed description of the bug.  Use the template below as necessary
      value: |
        Branch Name: eg. Dev, Main or https://github.com/USERNAME/REPO-NAME

        Reproduction Steps:
          1. Go to ''...'
          2. Click on '...'
          3. Scroll to '...'
          4. See Error

        If applicable, screenshots can be attached to better explain the problem:
        ![LINK-ALT-TEXT](LINK.png)

        Copy and Paste any relevant Logs:

        > Paste Logs here

        Utilize the dropdown below, or describe the impacted environment:

        > How/Where are you building.
        
      render: bash  
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: false
      options:
        - Windows (Direct Clone)
        - Windows (Shared Folders)
        - Linux (Direct Clone)
        - Linux (Shared Folders)
        - Mac (Direct Clone)
        - Mac (Shared Folders)
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Optional: Please apply any labels or types as necessary - leave blank for unknown."
