name: "Bug Report"
description: Create a new ticket for a bug.
labels: [
  "Bug"
]
body:
  - type: markdown
    attributes:
      value: |
        Define the problem.

        Capture the setup:
        * Which branch and git hash used
        * Any changes in configuration

        Steps to recreate:
        * ...

        Add logs or screenshots as desired.
                
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows (Direct Clone)
        - Windows (Shared Folders)
        - Linux (Direct Clone)
        - Linux (Shared Folders)
        - Mac (Direct Clone)
        - Mac (Shared Folders)
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Optional: Please apply any labels or types as necessary - leave blank for unknown."
